apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: patch.yaml
images:
- name: 414772274275.dkr.ecr.ap-south-1.amazonaws.com/hello-api-dev-hello-api
  newName: 414772274275.dkr.ecr.ap-south-1.amazonaws.com/hello-api-dev-hello-api
  newTag: eac2462f528758a59e5d722dc515247147be8b47
