apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: patch.yaml
images:
- name: 414772274275.dkr.ecr.ap-south-1.amazonaws.com/hello-api-dev-hello-api
  newName: 414772274275.dkr.ecr.ap-south-1.amazonaws.com/hello-api-dev-hello-api
  newTag: 8c1f2190a2713cba5f29af076e32ba5d40edbdc2
