name: Build and Push to ECR

on:
  push:
    branches:
      - main
    paths-ignore:
      - "kustomize/**"

permissions:
  contents: write

jobs:
  docker:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run Tests
        run: go test ./...

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        run: |
          docker build \
          -t ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} \
          .

      - name: Tag Image
        run: |
          docker tag \
          ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Push Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Install Kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update Image Tag
        run: |
          cd kustomize/overlays/dev

          kustomize edit set image \
          414772274275.dkr.ecr.ap-south-1.amazonaws.com/hello-api-dev-hello-api=414772274275.dkr.ecr.ap-south-1.amazonaws.com/hello-api-dev-hello-api:${{ github.sha }}

      - name: Commit Image Update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add kustomize/overlays/dev/kustomization.yaml

          git diff --cached --quiet || \
          git commit -m "Deploy image ${{ github.sha }}"

      - name: Push Changes
        run: git push